### ISSUE TITLE
請問有要開放原始碼嗎？

### ISSUE THREAD

**Issue by BirkhoffLee** [RossWang/Aria2-Integration#1]
如題，如果有的話大家可以一起改進

**Comment by RossWang** [comment]
如果你要看原始碼，插件直接解壓就有
至於上傳到github要等等，因為這是我第一次提交給AMO，有一些審查問題要解決，所以可能會有大改動。
我怕到時候大家提交的程式會不能用

**Comment by BirkhoffLee** [comment]
了解
