### ISSUE TITLE
文件名中的`/`应该被处理

### ISSUE THREAD

**Issue by Aetf** [RossWang/Aria2-Integration#10]
如果下载文件名中含有文件系统不允许的字符，比如 `/`，那么在添加下载任务的时候应该把特殊字符替换掉，否则创建的下载文件有问题（`/`之前的部分被认做文件夹名，下载得到的文件不完整）。

可以用 Google Doc 做测试，新建一个含有特殊字符的文档，然后选择导出 pdf。

火狐默认的行为是替换成`_`：`1/2/3.pdf` => `1_2_3.pdf`
![image](https://user-images.githubusercontent.com/1519759/33633210-0272b732-d9de-11e7-88de-477514d56cb9.png)

Aria-Integration 的行为
![image](https://user-images.githubusercontent.com/1519759/33633263-336a6394-d9de-11e7-9d7e-946c099f97d2.png)
不管点击 Download 还是 Save 都没有处理文件名

**Comment by RossWang** [comment]
看起來有點複雜，下一版會修正
https://stackoverflow.com/a/31976060
