### ISSUE TITLE
错误：Loop range missing

### ISSUE THREAD

**Issue by no1xsyzy** [RossWang/Aria2-Integration#12]
因为是拦截下载，所以`parameterized-uri`应该默认（始终）为`false`。

**Comment by RossWang** [comment]
不懂你的意思，這個擴展從來就沒有使用parameterized-uri，更沒有去打開它啊

**Comment by no1xsyzy** [comment]
emmm，是我的aria2配置文件默认打开了
但既然是拦截下载，应该在无论客户端设置的情况下关闭`parameterized-uri`标志。
推测有相当多的aria2用户配置打开此标志的（因为我这个配置基本是从别的地方复制的）

**Comment by RossWang** [comment]
不好意思，一直忘記回
我可能做個提示，不做自動關parameterized-uri的功能
 
有人應該會需要parameterized-uri

**Comment by no1xsyzy** [comment]
你这个是捕获下载，应该不会出现parameterized-uri吧
只要加任务的时候设置不用就行了

**Comment by RossWang** [comment]
原來這個Scope不是Global的

好吧，下一版改
