### ISSUE TITLE
Blank Download Window

### ISSUE THREAD

**Issue by ibrokemypie** [RossWang/Aria2-Integration#13]
On linux the download window dialogue seems to be blank every time.
![image](https://user-images.githubusercontent.com/7827846/34512906-62acedb0-f0b9-11e7-851e-1e991d50bd34.png)

**Comment by RossWang** [comment]
Refer to
https://github.com/RossWang/Aria2-Integration/issues/6#issuecomment-345519899

**Comment by RossWang** [comment]
Resolve in Firefox 63
