### ISSUE TITLE
Can't figure out how to integrate with aria2

### ISSUE THREAD

**Issue by philgoetz** [RossWang/Aria2-Integration#14]
I installed this extension in Firefox 57.0.2 64-bit on Windows.
The web page from which I downloaded it says:

> You need to download and start Aria2 by yourself, complete at least 'Protocol,' 'Host,' 'Port' and 'Interface' in the options page and then click the 'Save' button.
>
>If you don't want to start Aria2 manually, just write a program to start Aria2 in the background and register it to the system's 'autostart' or 'uri scheme.'

aria2c.exe is an executable. If I run it, it opens a terminal for about 1/20th of a second and then exits. If I run it from a terminal, it tells me it needs options, and exits. If I type "aria2c.exe -h" to get a list of its options, there are no options for protocol, host, port, or interface.  There is certainly no "options page", and no way to run it in the background without assigning it a task, since it is strictly command-line.

In the reviews, the author advises people to go to https://github.com/RossWang/Aria2-Integration/tree/master/Bin and download aria2.zip.  But that file says it is to update aria2 to version 1.33.1, which I already have, since I just installed aria2 right now.

I have no idea how to use this extension with aria2.

**Comment by no1xsyzy** [comment]
You should start up an aria2 RPC server ([reference for aria2c](https://aria2.github.io/manual/en/html/aria2c.html#rpc-options)). You can also see detailed configurations about rpc with `aria2c --help=rpc`.
<https://github.com/RossWang/Aria2-Integration/tree/master/Bin> provides an `aria2.conf` file for minimum configurations, with a bundle of start up utils.
Options page refers to the extension option page. It can be found at `about:addons`.

**Comment by RossWang** [comment]
Did you solve the problem?

**Comment by tanmay-das** [comment]
@RossWang I can't configure it either. This is what I tried:

Installed aria2 using: `sudo apt-get install aria2`
Ran this command to start RPC server: `aria2c --enable-rpc=true`
Attempted to download a file, download manager prompted, clicked download and it exited saying "You need to config first"

**Comment by tanmay-das** [comment]
Figured it out at last. You have to go to one of your rpc server settings and manually click on the "save" button. Once you see "options saved", you are ready to go. Make sure aria2c is running in the background.

**Comment by RossWang** [comment]
I'm going to close this issue.
If you still have problems, feel free to leave some messages here.
