### ISSUE TITLE
错误地阻挡RSS订阅

### ISSUE THREAD

**Issue by chenjiajia9411** [RossWang/Aria2-Integration#15]
开启下载集成的时候，点击RSS订阅的时候会自动弹出下载框，没有办法被火狐内置RSS订阅识别。
版本是AMO最新版0.2.4，火狐版本是Nightly 59.0a1。

**Comment by RossWang** [comment]
好的，我會修正

不過可能會讓你等有點久，因為我現在大改動改到一半沒辦法發布

**Comment by chenjiajia9411** [comment]
没关系，谢谢您给我们带来这么好的附加组件！

**Comment by no1xsyzy** [comment]
你可以做一次commit，然后从稳定版本开新branch。
之后可以再merge。
git最初的用法就一直这么干的。
