### ISSUE TITLE
百度云盘下载不了

### ISSUE THREAD

**Issue by htshts1115** [RossWang/Aria2-Integration#17]
我设置好了aria2，可以下载115，但是百度网盘的文件下载不了：点击下载可以弹出链接，选择下载aria2Ng显示创建了新任务，然后马上就变成已停止任务。可能是链接解析错了？
禁用了插件后使用浏览器默认下载可以正常下载百度云文件。
请问怎么解决？谢谢

**Comment by RossWang** [comment]
這個目前要帳號，可是我沒有，沒辦法測試

大家看看甚麼問題，可以告訴我或提個PR

**Comment by no1xsyzy** [comment]
百度云期望处理超过其能处理的事务，请用用户脚本拉地址

**Comment by RossWang** [comment]
> 百度云期望处理超过其能处理的事务，请用用户脚本拉地址

用用户脚本拉地址一樣要登錄啊

**Comment by no1xsyzy** [comment]
我是说用用户脚本拉才能用aria2下载，可能是正常下载地址限制UA
另外，别人分享的就不用登录（甚至有段时间不登录速度更快；不登录500K/s，登录直接变10K/s(免费账号不如游客)）

**Comment by RossWang** [comment]
還是說UA要是這種
netdisk;5.2.7;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia

**Comment by no1xsyzy** [comment]
UA不清楚，可以试一下。
这种情况下不妨做一个下载设置替换（在下载捕获的界面）。比如钩上“百度UA”就可以把UA换成这种。（可以是下拉或者触发器）
这样用户也可以自己配置一些（虽然一般感觉用不到，但感觉可以直接解决将来10%的issue）

**Comment by RossWang** [comment]
現在又開放免登入下載了，經測試只要開啟傳遞UA即可下載
