### ISSUE TITLE
SSL/TLF handshake failure: unable to get local issuer certificate

### ISSUE THREAD

**Issue by icering** [RossWang/Aria2-Integration#19]
无法下载。无论是BT种子还是百度网盘，点击下载之后任务在“AriaNg->下载->已完成/已停止”里，任务状态为“SSL/TLF handshake failure: unable to get local issuer certificate”。
直接在AriaNg里打开种子下载正常。

**Comment by RossWang** [comment]
甚麼系統

**Comment by no1xsyzy** [comment]
确认是否安装了ca-certificates包或者ca-bundle包。
没有安装CA根证书导致无法确认网址可信性。

**Comment by RossWang** [comment]
問題解決了嗎？

**Comment by RossWang** [comment]
先關閉，如果還有什麼問題歡迎提出
