### ISSUE TITLE
關於多伺服器與使用內建 AriaNg 的問題

### ISSUE THREAD

**Issue by BirkhoffLee** [RossWang/Aria2-Integration#2]
作者大大你好 <(_ _)>

請問一下，Aria2-Integration 支援多 aria2 伺服器設定嗎？

另外，此套件是自己發 request 給 RPC server，然後使用 AriaNg 來管理是嗎？

**Comment by RossWang** [comment]
1. Aria2-Integration 目前不支持多 aria2 伺服器設定
2. 是的

話說，如果要支持多伺服器該用甚麼方法實現啊，應該不會是同時發Request 給所有伺服器吧？

**Comment by BirkhoffLee** [comment]
@RossWang 可以參考 https://github.com/acgotaku/BaiduExporter

多伺服器是用來切換的，例如你可能要把 A 檔案下載到家裡的 router 上，B 檔案傳到公司的伺服器上這樣。就是下載的時候選一個的意思
