### ISSUE TITLE
新特性不起作用“Context menu now has sub-menu to select the RPC server”

### ISSUE THREAD

**Issue by sishentibu** [RossWang/Aria2-Integration#21]
看更新日志，最新版是可以在右键子菜单直接选择 rpc 服务器吧？
我在ff58下还是没有出现子菜单，还是跟原来一样。点下载后出现一个对话框，在对话框的“高级”中选择rpc服务器。
是需要哪里设置？

**Comment by RossWang** [comment]
因為我想說下載視窗有相同功能
所以設計成如果打開下載視窗的話就不會出現子選單

**Comment by sishentibu** [comment]
在ff58下，能不能实现这种操作的（跟以前的xthunder的操作类似）：
一直都显示主菜单与子菜单；
在主菜单左键单击的时候，显示子菜单；
在主菜单右键单击的时候，显示选项框。



2018-02-24

**Comment by RossWang** [comment]
你說的菜單是哪個菜單

**Comment by sishentibu** [comment]
@RossWang 
![qq 20180224222801](https://user-images.githubusercontent.com/13832182/36631396-0c614f6a-19b2-11e8-8348-982433bbc97a.jpg)

**Comment by RossWang** [comment]
這種菜單的話應該是不行，API沒辦法控制那麼多

不過你說的

> 一直都显示主菜单与子菜单； 在主菜单左键单击的时候，显示子菜单； 在主菜单右键单击的时候，显示选项框。

我很沒有畫面，這菜單一直顯示幹嘛啊

**Comment by sishentibu** [comment]
我是从我自己的需求出发的。
我是根据下载的链接来选择是用aria2下还是用自带的下载。比如说需要走代理的链接，就是用自带的下载方便点。
-------
刚刚想到个替代办法：
就按你现在的设置，设置成显示子菜单的。要想用自带下载，就把工具栏中的开关关掉。这样就是要开开关关，有时就忘记了。

**Comment by RossWang** [comment]
所以沒問題了吧
我們可以把這個Issue關了嗎？

**Comment by genkagen** [comment]
可否在Add-ons Option添加選項，刪除上圖右鍵Menu中"RPC Server 2/RPC Server 3"，多了一重點選Menu的動作，快速下載效率變低了。
