### ISSUE TITLE
新建下载后，新建下载界面不正常显示

### ISSUE THREAD

**Issue by acoret** [RossWang/Aria2-Integration#25]
新建下载界面是**空白的**！！  
> 通过修改宽度或高度即双击放大什么的就会恢复正常

**Comment by acoret** [comment]
右键点击也会显示界面

**Comment by RossWang** [comment]
Duplicate
https://github.com/RossWang/Aria2-Integration/issues/6#issuecomment-349162870

官方不修我也沒有辦法
