### ISSUE TITLE
每次重启后内置的AriaNG的RPC地址都会自动改成

### ISSUE THREAD

**Issue by aunsen** [RossWang/Aria2-Integration#26]
每次重启后内置的AriaNG的RPC地址都会自动改成30d6ec99-9809-4486-949d-681e6be3e74d这样的地址而不是默认的localhost，每次都要手动修改才能链接上aria，很恼火，求修复！
还有另一个问题就是用另存为下载卡饭的附件无法下载，必须用aria才能下载成功

**Comment by aunsen** [comment]
就是火狐重启，是不是跟我每次关闭火狐之前清理历史记录和缓存以及脱机网站数据有关

**Comment by RossWang** [comment]
和脱机网站数据有關

不過擴展內有一個設置可以在每次按下詳細按鈕後配置一次AriaNg

**Comment by aunsen** [comment]
果然，我一清除脱机网站数据AriaNg的地址就里面变成30d6ec99-9809-4486-949d-681e6be3e74d
逼死强迫症啊

**Comment by RossWang** [comment]
還有問題嗎？應該可以關閉這個Issue了吧

**Comment by aunsen** [comment]
可以关闭了，谢谢

**Comment by abolast** [comment]
谢谢解答！原来是Firefox的API限制问题o(*￣▽￣*)o
