### ISSUE TITLE
login/pass authentication

### ISSUE THREAD

**Issue by mrrdmr** [RossWang/Aria2-Integration#27]
Could you add login/pass authentication (not by token) please?

**Comment by no1xsyzy** [comment]
If my memory is right, you can use `<username>:<password>` as the token (a colon `:` between username and password). That's just the way the old authentication works.

**Comment by mrrdmr** [comment]
I've tried but no luck. Can't connect to aria2.

**Comment by RossWang** [comment]
https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-rpc-passwd
![image](https://user-images.githubusercontent.com/13231557/40237150-2984d8ac-5ae2-11e8-83f8-ae20efddaa21.png)

`--rpc-passwd` option will be deprecated in the future release of Aria2, so I will never going to add this option.

But if one want to submit a Pull Request, I will take it.
