### ISSUE TITLE
Can't use RPC Server 2&3 with https/wss protocol

### ISSUE THREAD

**Issue by nyfair** [RossWang/Aria2-Integration#28]
使用default server和内置ariang的时候都是正常的
设置如图
![1](https://user-images.githubusercontent.com/1343411/40129902-1892b7b0-5968-11e8-8e53-5ab4545f5110.png)
debug状态下，会发现浏览器实际请求的是http protocol
![2](https://user-images.githubusercontent.com/1343411/40129932-2db84696-5968-11e8-9017-656fead06501.png)

**Comment by nyfair** [comment]
#29 
https://github.com/RossWang/Aria2-Integration/pull/29/commits/527d5bf70266295d1170d8af744cfdff749fce33

**Comment by RossWang** [comment]
Merged, will be fixed in the next release.
Thanks.
