### ISSUE TITLE
点击下载后会弹出ERROR

### ISSUE THREAD

**Issue by amaothree** [RossWang/Aria2-Integration#3]
问题描述：当点击下载链接并在弹出的对话框里点击下载会弹出如下截图：
![screenshot from 2017-10-27 12-34-46](https://user-images.githubusercontent.com/26244249/32145580-0520e962-bd06-11e7-9c33-ff1869a63652.png)
但事实上，在我重装系统前，并没有这个出现，只有重装后才出现的。重装前后我的设置并没有变化。、

OS：Arch Linux
Kernel：x86_64 Linux 4.13.9-1-ARCH
FireFox：56.0.2 (64-bit)

**Comment by RossWang** [comment]
這個訊息是在Timeout或是或http返回非200的時候顯示
如果每個網站都如此的話，通常是因為Aria2 沒開或是rpc secret錯誤

**Comment by amaothree** [comment]
你好，我檢查了一下，我確認我沒有設置任何的secure和token。我的rpc是正常的，因爲我可以複製下載地址然後打開您內置的AriaNG進行下載（AriaNG顯示已連接）。

**Comment by RossWang** [comment]
不然你進入about:debugging，看看有什麼log
或是你自己除錯看看

**Comment by amaothree** [comment]
非常不好意思，我的確不懂JS，只能貼出log：
`TypeError: invalid 'in' operand browser[Learn More]  tabbrowser.xml:2346:1
"{"jsonrpc":"2.0","method":"aria2.addUri","id":"ext","params":["token:",["https://codeload.github.com/RossWang/Aria2-Integration/zip/master"],{"header":["Referer: https://github.com/RossWang/Aria2-Integration","Cookie: logged_in=yes; _octo=GH1.1.359585869.1508920476; _ga=GA1.2.968193591.1508920476; dotcom_user=amaothree; _gat=1"],"out":"Aria2-Integration-master.zip","dir":"/home/amao/Downloads/"}]}"  common.js:96:5`

**Comment by RossWang** [comment]
你試一下新版看會不會有問題

**Comment by amaothree** [comment]
问题已经解决。
现在只是遇到了和NanerLee一样的问题，具体情况和他的描述是一样的。

**Comment by RossWang** [comment]
> 现在只是遇到了和NanerLee一样的问题，具体情况和他的描述是一样的。

以前會這樣嗎，從什麼時候開始的？

**Comment by amaothree** [comment]
升级为Firefox 57后。
