### ISSUE TITLE
Optionally Skip Confirmation Window

### ISSUE THREAD

**Issue by Rictusempra** [RossWang/Aria2-Integration#30]
![image](https://user-images.githubusercontent.com/16912240/40411104-fe4ecfb4-5e5e-11e8-95f9-d205ce2e91e4.png)

Fetch filename form server & require users to determine a location first so that this window can be override.

**Comment by nyfair** [comment]
I think aria2 is smart enough to guess file name.
How about reusing the "Display Download Panel" option for this?
https://github.com/nyfair/Aria2-Integration/commit/402419eb4d1ad10ba7f1d08186d073459ad3ad26#diff-a8ac1482f74270610ac42d3563300aa9
