### ISSUE TITLE
filter setting cannot be saved

### ISSUE THREAD

**Issue by wynzz** [RossWang/Aria2-Integration#31]
文件大小限制不起作用/无法保存设置
The setting of filter for file size cannot be saved .

**Comment by raidenii** [comment]
Same issue here, even with release 0.5.
e.g. Set a minimum file size that triggers Aria2c to 1,048,576 bytes (10MBytes), and for the excluded file type, type application/x-bittorrent, yet torrent files downloads are still intercepted by Aria2 Integration.

**Comment by RossWang** [comment]
For the excluded file type, try other sites (ex. rarbg).
Some servers do not send us file type.

**Comment by raidenii** [comment]
I tested it with rarbg.

**Comment by raidenii** [comment]
For file type filtering, it seems that this extension will not accept more than 1 file type. I suppose the format is one file type each line in that textbox?
E.g., If I tried to exclude two file types, .torrent and .txt, I put

application/x-bittorrent
text/plain

Yet both file types are still intercepted. If I put only application/x-bittorrent, then the filter works.

**Comment by RossWang** [comment]
Because I am lazy, it does not support multi-line input.

You can type `application\/x-bittorrent|text\/plain` to do the same things.

Details at https://regex101.com/

**Comment by raidenii** [comment]
Oh OK, good to know it's a one-liner.
How about size filtering? I can confirm that size filtering is still not working.

**Comment by raidenii** [comment]
Actually I tried and no. Still, the file type after the pipe were intercepted.

**Comment by RossWang** [comment]
> Actually I tried and no. Still, the file type after the pipe were intercepted.

 Make sure there is only one line in the text area. (without `\n`)

**Comment by raidenii** [comment]
Thanks, that works.
