### ISSUE TITLE
下载 115 网盘文件，发生错误（22）

### ISSUE THREAD

**Issue by GreyChou** [RossWang/Aria2-Integration#32]
![2018-06-30 14 41 35](https://user-images.githubusercontent.com/12140363/42123393-097ca922-7c84-11e8-8b9e-05be3ac474bf.png)

**Comment by RossWang** [comment]
有傳遞User-Agent嗎？
或者是說，User-Agent 相同嗎？

**Comment by RossWang** [comment]
還有問題嗎？
我先關閉這個Issue，如果還有問題我再Reopen
