### ISSUE TITLE
AriaNg RPC Settings are being overwritten in Firefox.

### ISSUE THREAD

**Issue by lss4** [RossWang/Aria2-Integration#33]
OS: Manjaro Linux (Kernel: 4.17.5-1-MANJARO)
Firefox: 61.0.1 (64-bit)

~~I have RPC Secret Token configured for aria2 which I could add into the AriaNg settings page to get it connected to the aria2 daemon, but the setting is only effective within the current settings tab, and only works when reloading the same settings tab. It is not saved globally. When opening a new settings tab I'll be greeted with the same "Authorization failed." error and in the AriaNg settings the RPC Secret Token settings became empty again. Of course, downloads won't work because the download page won't know about my RPC Secret Token, either.~~

EDIT: After some testing it seems something is actively overwriting the active profile's configurations.
If I add a new profile with the proper settings, but do not activate it, the profile will remain intact after opening a new configuration tab, but when the created profile becomes active, the settings will be overwritten.

When a profile is active, the profile's settings are being actively overwritten into
Aria2 RPC Alias: (empty, default, which is 127.0.0.1:6800)
Aria2 RPC Address: ws://127.0.0.1:6800/jsonrpc
Aria2 RPC Protocol: WebSocket
Aria2 RPC Secret Token: (empty)

And the overwritten settings are saved, because when I switch to another profile, the overwritten profile did not revert to the way I previously configured.

I'm not exactly sure why this happens, but given the fact that downloads never worked means the overwritten settings are always in effect, making the extension useless.

I tried saving sessions when it's connected (with proper settings), but it doesn't work, either.

EDIT2: After looking at the source code a bit I think the profile settings being overwritten seem to match those defined inside the config.js (config.command.guess). But settings in the Global Settings tab can still be saved properly.

**Comment by RossWang** [comment]
There is a function in the add-on that can configure AriaNg automatically.
If you don't want it, there is a setting to disable this function.
![1](https://user-images.githubusercontent.com/13231557/43006164-951470ee-8c67-11e8-9904-8d21d40bc82d.png)

**Comment by lss4** [comment]
This corrects my issue and AriaNg could connect to my daemon, but downloads still don't work.
Guess I'll need to check my settings a bit further...
It took me a while to figure out I need to check the extension's properties page rather than only the details page.

And yeah, should be saying that this setting is better not enable by default as it can get in the way for some users.

Closing the issue.
