### ISSUE TITLE
download integrity problem

### ISSUE THREAD

**Issue by free-birds** [RossWang/Aria2-Integration#34]
when i use this add-on to download files from url: https://www.winitor.com/binaries.html ,click 'save' or 'save as' ,not using aria2.
 after finished, i checked the sha256, it didn't match.
when i disable this add-on, using firefox's built-in downloaded ,it's ok. 

and this url: http://exeinfo.atwebpages.com/ ,it's the same situation, even worse, it can't download the whole file,just several KB , the original one is 1.8MB.

**Comment by RossWang** [comment]
I can only reproduce the issue with Opendrive in the second link.
It's the limitation of Webextension Download API, we cannot specify some HTTP header.

Reference:
https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download

**Comment by RossWang** [comment]
Is there any other problem?
If there is no problem, I will close this issue.

**Comment by free-birds** [comment]
OK,thank you!

-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Apr 5, 2019, 3:07 AM by notifications@github.com:

**Comment by RossWang** [comment]
Thanks.
