### ISSUE TITLE
無法下載 dfpan.com上面的檔案

### ISSUE THREAD

**Issue by zxp8466** [RossWang/Aria2-Integration#35]
您好，我找到一個檔案是放在http://page2.dfpan.com這個網站上。
我可以用網頁直接下載，但改用本工具轉到aria2卻都是下載失敗。
其他網站的一搬鏈接都是可以轉aria2的，就這個網站不行。
請問有解決辦法嗎？

**Comment by RossWang** [comment]
給個連結吧

**Comment by zxp8466** [comment]
[例如這個鏈結。](http://page2.dfpan.com/fs/fbor0ing6mancc0865/)
使用插件可以看到轉由底下網址下載，但點確認後AriaNg頁面卻會立刻跳轉到結束並顯示失敗。
http://100.42.29.162/view?action=downfile&fid=boringmanf06cc0860f4e748b

**Comment by RossWang** [comment]
目前Aria2似乎不支持HTTP POST方式的下載
未來此插件可能不會攔截HTTP POST引發的下載

你也可以到Aria2那邊問問未來有沒有可能支援HTTP POST

**Comment by zxp8466** [comment]
了解，原來是aria2不支援的關係。
感謝幫忙分析..........
