### ISSUE TITLE
Download url not urlencoding parentheses

### ISSUE THREAD

**Issue by thorsummoner** [RossWang/Aria2-Integration#36]
I've had files whos names contain parentheses `(` or `)` fail to register for download, when replacing `(` with `%28` an `)` with `%29` manually resolve the issue

**Comment by RossWang** [comment]
Can't reproduce this issue.
Can you provide more information about this issue?
For example, in what part it failed? Before, during or after download panel?

**Comment by thorsummoner** [comment]
we're you able to reproduce? i suspect the issue was due to the external
party's server side URL routing incapabilities, this will hopefully save me
a bunch of headache :) thank you
