### ISSUE TITLE
Downloading with aria only via context menu

### ISSUE THREAD

**Issue by woj-tek** [RossWang/Aria2-Integration#37]
Hi,
I love the project but it would be great to be able to download with aria only on demand (by selecting from context menu) and by default (on click) using Firefox default tool.

I went over the options and successfully enabled context menus and they work like a charm, but I wasn't able to disable hickjacking normal clicks.

(this is a copy/followup to https://github.com/mayswind/AriaNg/issues/284)

**Comment by RossWang** [comment]
Hi, you can turn it off with the toolbar button.
![image](https://user-images.githubusercontent.com/13231557/50270617-1f06da80-046d-11e9-8e6f-68aa3f89021d.png)

**Comment by RossWang** [comment]
Is there any other problem?
If there is no problem, I will close this issue.
