### ISSUE TITLE
建议：改进扩展选项中关于页面“扩展主页”指向

### ISSUE THREAD

**Issue by ivysrono** [RossWang/Aria2-Integration#38]
![default](https://user-images.githubusercontent.com/2649544/46527863-e2433280-c8c4-11e8-8f9e-5fc8d2af8da8.png)
我看了下其他地方都是没有这个 zh-* 的，这里也删掉吧。

**Comment by Mapaler** [comment]
那个语言代码删掉，服务器会自动识别语言跳转，确实应该删掉。
