### ISSUE TITLE
建议：合并扩展弹出页面和详情页面

### ISSUE THREAD

**Issue by ivysrono** [RossWang/Aria2-Integration#39]
现在点击图标的弹出选项让人很迷惑，我就没看明白那个开关是：
关闭扩展？
关闭主程序？
……
反正下载中我没敢试。
其实可以直接进入详情页面，开关做在那里面
—— 如果是因为用的 Ng 项目不方便修改的话，还请明确下这个开关究竟啥意思吧。

**Comment by Mapaler** [comment]
那个开关石临时关闭扩展，为了让一些无法下载的文件可以正常下载的。不会影响Aria2

**Comment by icefed** [comment]
对，大部分时候只是想点击按钮打开ng管理界面，但是现在是多点了一层，而且经常会出现点击弹出小框会BUG无法显示完全要多点几次。
<img width="88" alt="image" src="https://user-images.githubusercontent.com/3964419/55791475-24a63000-5af1-11e9-8887-ed389eb63da4.png">

@RossWang
