### ISSUE TITLE
AriaNg's RPC config lost after clear browser history

### ISSUE THREAD

**Issue by mercurylmy** [RossWang/Aria2-Integration#4]
清除历史后 AriaNg 的 RPC 配置会消失，附加组件的选项面板里的配置仍在。希望能在打开 AriaNg 时，自动恢复配置。

**Comment by RossWang** [comment]
這是AriaNg的原始行為，他把配置存在Offline Storage
https://github.com/mayswind/AriaNg

我不太會前端，如果要改的話可能會花點時間，目前我傾向不去動他，先完善我的擴展
這樣未來原作者的更新也好套用

**Comment by mercurylmy** [comment]
`/data/action/index.js`
38 行
`url: "../../data/ariang/index.html"`
改成
`url: "../../data/ariang/index.html#!/settings/rpc/set/" + protocol + "/" + host + "/" + port + "/" + interf + "/" + btoa(token);`
类似的行吗

**Comment by RossWang** [comment]
有道理

不過因為有人可能要不同的設定，我會再做一個設定選項之後再發佈
