### ISSUE TITLE
建议：点击右键顶层直接使用默认服务器下载

### ISSUE THREAD

**Issue by ivysrono** [RossWang/Aria2-Integration#40]
大多数人只会用一个服务器吧。
或者是有几个服务器得到了设置就显示几个，如果只有一个，那就只有一层菜单。

**Comment by Mapaler** [comment]
我倒是觉得应该自定义服务器数量和名称才对，默认、1、2根本不记得哪个是哪个

**Comment by rv2900** [comment]
Would appreciate with customize server quantity and customize server name. different names refer to different paths on the nas. thanks!
