### ISSUE TITLE
奶牛快传下载出错

### ISSUE THREAD

**Issue by smzh369** [RossWang/Aria2-Integration#43]
https://cowtransfer.com/s/0a00325ffeb142
左键单击下载读不到cookie，右键链接“使用Aria2下载”正常

**Comment by RossWang** [comment]
不能覆現

**Comment by smzh369** [comment]
试了下新版已解决

**Comment by smzh369** [comment]
网站更新，又无法下载了https://c-t.work/s/eab6a04c10154c，AriaNg显示http返回头无效或无法识别，现在右键也无法获取到下载链接，直接点保存也不行。关掉扩展能用浏览器下载

**Comment by no1xsyzy** [comment]
限制似乎是同一个 URL 不允许被请求两次——连 Firefox 自带的断点续传都失效了。
无能为力，除非专门为此网站做处理，而这几乎是不可能的。
如同百度网盘那样专门找个工具或者 Userscript 吧。

**Comment by smzh369** [comment]
网站更新后正常了
