### ISSUE TITLE
请求发布aria2hide.exe文件的32位版本

### ISSUE THREAD

**Issue by liuxb** [RossWang/Aria2-Integration#44]
请求作者发布一个aria2hide.exe文件的32位版本，不然32位系统中不能实现自动开启关闭功能。。。
谢谢！

**Comment by no1xsyzy** [comment]
不妨自己用 MinGW 编译一下？

**Comment by Mapaler** [comment]
我是直接用BAT和VBS写的

**Comment by RossWang** [comment]
因為32bit版本部分防毒軟體報毒，不適合上傳github
我的電腦也不方便留著，所以就不上傳了
