### ISSUE TITLE
出现无法调用本扩展的URL

### ISSUE THREAD

**Issue by Mapaler** [RossWang/Aria2-Integration#45]
在此页面下载VirtualBox Extension Pack
https://www.virtualbox.org/wiki/Downloads
连接地址是
https://download.virtualbox.org/virtualbox/5.2.22/Oracle_VM_VirtualBox_Extension_Pack-5.2.22.vbox-extpack
直接点击，本扩展没有反应，右键菜单主动点击，扩展不会自动填充文件名
![image 1](https://user-images.githubusercontent.com/6565860/48641726-b1066800-ea15-11e8-811e-90ac77a9d5c4.png)

**Comment by RossWang** [comment]
無法解決
瀏覽器是透過分析檔案內容做的，如果擴展要做的話太麻煩，又沒有效率
