### ISSUE TITLE
Zeal下载失败

### ISSUE THREAD

**Issue by lonelykid** [RossWang/Aria2-Integration#46]
https://zealdocs.org/download.html
403。右键或者左击都不行。打开user-agent也不行

**Comment by lonelykid** [comment]
Anaconda下载失败...
https://www.anaconda.com/download/
😰...之前在chrome上用camtd基本没遇到过问题的，是firefox的api限制了么

**Comment by RossWang** [comment]
無法覆現，需要更多詳細資訊

**Comment by RossWang** [comment]
沒有其他問題的話，我要關閉這個issue囉

**Comment by lonelykid** [comment]
的确可能当时是我的问题，谢谢。
