### ISSUE TITLE
无法接管由按钮弹出来的下载页面

### ISSUE THREAD

**Issue by hhaoao** [RossWang/Aria2-Integration#48]
如图，这种按钮下载的弹出来的下载连接无法接管。
https://newsupport.lenovo.com.cn/driveList.html?fromsource=driveList&selname=Lenovo%20g5005
![default](https://user-images.githubusercontent.com/11269610/49707804-f2321680-fc67-11e8-9c2b-f034f76c32dc.png)

**Comment by no1xsyzy** [comment]
1. 右键是没有用的，要分析通过 click event 的 JavaScript 代码决定的下载 URL 需要写元语言解释器（因为需要钩掉对 window.location.href 的修改），这在 JavaScript 下是个大活，或许可以找一下有没有这种项目，作为 submodule 引入。
2. 写这个网站的后端的人很白痴地将下载文件写成 `inline` 了。
![default](https://user-images.githubusercontent.com/7346170/50260203-42686000-0442-11e9-9ac3-43004750e5ce.png)

@RossWang 如下修改有效：
1. 即使是 `inline`，写了 `filename` 或者 `filename*` 的都要钩掉，修改 [App/common.js#L627](https://github.com/RossWang/Aria2-Integration/blob/713c86755887f791ace31d7e7ae6917dd7a36de8/App/common.js#L627)；
2. 即使是 `inline`，`content-type` 不是能直接显示的也直接钩掉；
3. 不管其他，只要是 `content-type: application/x-msdownload` 必然钩掉；

**Comment by RossWang** [comment]
已修正，忘記寫進commit了
https://github.com/RossWang/Aria2-Integration/commit/7ad7018d0baeb3292de71f857517f0b430a726cc
