### ISSUE TITLE
文件名识别重复

### ISSUE THREAD

**Issue by shingoxray** [RossWang/Aria2-Integration#53]
下载对话框的文件名会重复2次，中间是%3Bfilename%3D。
<img width="309" alt="微信截图_20190404101113" src="https://user-images.githubusercontent.com/6487392/55525133-6afb2980-56c2-11e9-88f1-038b3e85b366.png">

**Comment by no1xsyzy** [comment]
即 URL 编码的 `;filename=`，
可以提供一个直接可以下载的 URL 吗？如果不可以的话请想办法自己看一下 Content-Disposition 头里的内容。初步估计是服务器传出来的头是坏的。

**Comment by shingoxray** [comment]
奇怪，issue回复没有邮件提醒，问题已经解决了？

**Comment by RossWang** [comment]
ONEDRIVE 沒問題了
其他網站不知道會不會反而造成一堆問題...
