### ISSUE TITLE
弹出的下载页面, 内容无法正常显示

### ISSUE THREAD

**Issue by NanerLee** [RossWang/Aria2-Integration#6]
我是之前在插件下面评论的同学, 感觉问题没有描述清楚, 还是来这里说吧.

先放两张图

第一张图, 点击某个文件下载链接之后弹出来的, 上面无法显示内容
![2017-11-17 15-35-39](https://user-images.githubusercontent.com/16791509/32936055-aa025000-cbad-11e7-8c29-2173eed88fed.png)

第二张图, 用鼠标稍稍调整弹出页面的大小(放大缩小都可以)之后, 内容正常出现了
![2017-11-17 15-35-55](https://user-images.githubusercontent.com/16791509/32936069-b4143f22-cbad-11e7-8975-57547602f6d2.png)

这样的情景应该不是大小的问题的吧, 因为无论是放大还是缩小都可以显示内容.

**Comment by RossWang** [comment]
看上面的背景色好像連html都沒載入...
有沒有擴展衝突啊？
我這裡沒辦法複現，目前也還沒有想法，如果你有能力的話可以幫我調試下。

===============================================
因為Firefox57好像改成視窗太小就不會載入
像我貼出來的那邊如果設到一個數值以下，例如：零，Firefox就不會載入

**Comment by NanerLee** [comment]
首先应该不是扩展冲突的问题, 我禁用了所有其他扩展之后, 上述问题仍然存在.

然后我下载了你的源码包, 然后在foxfire中加载临时扩展, 可是无论我把 commom.js 中 popup 的高宽修改为任何值, 保存并重新载入后, 弹出的页面大小并没有改变, 上述问题仍然存在. 但是我在扩展的设置页面中设置高宽后, 弹出的页面大小有了变化, 但是是页面内容还是没有加载出来.

我对前端的东西不了解, 上面的调试也可能有很多错误的地方, 暂时我只能做到这个样子了...

**Comment by RossWang** [comment]
Download Panel 按下F12進入Developer Tool 看一下是否正常
如：滑鼠移到節點上，網頁元素會不會正確反白

**Comment by NanerLee** [comment]
在我在弹出的下载页面上按下f12时, 页面也会加载出来, 不过控制台那边有句话,

> 所用的 getPreventDefault() 已不赞成使用。请改用 defaultPrevented。

是API接口的原因?

**Comment by RossWang** [comment]
按下F12前記得先設定使用新視窗開啟Developer Tool，不然網頁顯示的大小改變就不準了

我好像沒有用到getPreventDefault()，所以應該不是這個問題

**Comment by NanerLee** [comment]
开发性工具里没有显示出什么错误信息, 下载页面的内容也没有加载出来, 网页也没有反白
![2017-11-18 16-02-03](https://user-images.githubusercontent.com/16791509/32978296-3a758450-cc7a-11e7-9695-d4c26514d526.png)

我猜会不会是电脑系统的原因, 我之后试试再跟你说吧

**Comment by RossWang** [comment]
![default](https://user-images.githubusercontent.com/13231557/32978449-6fa560c0-cc7d-11e7-920b-f28db33e3bce.png)
連這個都沒有啊

你可以看看下面這種載入方式正不正常
moz-extension://<uuid>/data/DownloadPanel/index.html

**Comment by amaothree** [comment]
遇到了同样的问题，所以排除应该不是个别现象，我是ArchLinux，看上面的截图，Lee用的也是Linux，而我出现这个情况的前后只有升级了Firefox57这一处变化，所以基本可以肯定是新版本火狐的问题，再具体是否是API或者是其他的，这方面我就不是很专业了。

**Comment by lxf1992521** [comment]
遇到了同样的问题，使用 Ubuntu 系统，FireFox 57 版本，需要改变下下载框的大小，下载确认信息页面才会出现。

**Comment by RossWang** [comment]
Reference
[Window created from contextMenus with browser.windows.create shows white screen even though DOM is there](https://bugzilla.mozilla.org/show_bug.cgi?id=1417394)

[Warning : Use of getPreventDefault() is deprecated. Use defaultPrevented instead in all page](https://bugzilla.mozilla.org/show_bug.cgi?id=1324190)

[chrome.windows.create() ignores titlePrefix and fails to paint content](https://bugzilla.mozilla.org/show_bug.cgi?id=1402110)

**Comment by Aetf** [comment]
[Bug 1408446: Add-ons that open Windows can get an empty window](https://bugzilla.mozilla.org/show_bug.cgi?id=1408446)
已经有了 patch 的样子，不过似乎近期没有更新。以及 [Bug 1400252](https://bugzilla.mozilla.org/show_bug.cgi?id=1400252) 可能也相关

**Comment by stardiviner** [comment]
遇到同样的问题

**Comment by RossWang** [comment]
Resolved in Firefox 63
