### ISSUE TITLE
建议：加入右键发送到aria的选单

### ISSUE THREAD

**Issue by daiaji** [RossWang/Aria2-Integration#60]
https://github.com/wadefelix/SendToAria2
以前用过这个 不过这个应用只能用右键发送

**Comment by no1xsyzy** [comment]
理论上来说有这个：
![图片](https://user-images.githubusercontent.com/7346170/59343794-3bf6d900-8d3f-11e9-9671-2eb0d5f3cc45.png)
但似乎并不能使用。

**Comment by RossWang** [comment]
> 但似乎并不能使用。

我這邊可以用耶

**Comment by daiaji** [comment]
@no1xsyzy @RossWang 在发了Issues之后几分钟
我发现了那个选项并找到了设置RPC 默认下载路径的地方……
 😂
试了一下似乎是有效的
