### ISSUE TITLE
請教如何禁用Dowload Panel？ 

### ISSUE THREAD

**Issue by genkagen** [RossWang/Aria2-Integration#7]
想要回之前的版本：在磁鏈接或種子鏈接上右鍵Menu -> Download with Aria2，不會彈出Download Panel，直接發送至Aria2立即下載。最新版本每次都要在Download Panel上點擊，效率變差了> _ <

**Comment by RossWang** [comment]
好的，我做一個選項來選擇要不要Download Panel
