### ISSUE TITLE
"dl.free.fr" can not get filename

### ISSUE THREAD

**Issue by BrittenV** [RossWang/Aria2-Integration#70]
test this:
_[deleted]_

**Comment by no1xsyzy** [comment]
The request does have `Content-disposition` header but it is malformed.

It reads:
```http
Content-disposition: filename=Heze_v1.7z
```

Correct:
```http
Content-Disposition: attachment; filename="Heze_v1.7z"
```

Cite: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition), [RFC-1806](https://www.ietf.org/rfc/rfc1806.txt), [RFC-2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html#sec19.5.1)

`attachment` is the magic word for this addon detect filename.
I am against fixing it here. You should contact operator of that website to fix this.

**Comment by BrittenV** [comment]
thank u for ur working

I ask for the webmasters,but they tell me:pls use browsers or other download applications……sadly.

(Yes, browsers recognize the filename correctly, but this extension not.)

**Comment by BrittenV** [comment]
Well,
your extension is up to you, my browser is up to me.
bye
