### ISSUE TITLE
Nothing, I've replaced it with another extension.

### ISSUE THREAD

**Issue by BrittenV** [RossWang/Aria2-Integration#71]
thank u

**Comment by no1xsyzy** [comment]
I think temporarily disable capturing should be enough. Click the toolbar button and it will show a small switch, which turns on/off the capturing.

**Comment by BrittenV** [comment]
most site catch by this ext,using aria2 through file server.
some site must download directly should disable this ext.

yes,the toolbar button is working,if someone downloads many files in short time,usually mistake(disabled for minitues by these site)

thank u for ur work

**Comment by no1xsyzy** [comment]
I checked the option menu and actually there is an option. I am not sure what's the localization, might be "excluded address".
![图片](https://user-images.githubusercontent.com/7346170/74235444-f6454280-4d09-11ea-89ec-ccda5cf346ae.png)
You need to use [Regular Expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) for this option without the wrapping `/`-s. It should be the download URL, not the referer.
For example, add `https?://.+\.githubusercontent\.com/.*` can exclude the picture I included above.

**Comment by BrittenV** [comment]
Thanks for your reply.
One last piece of advice from a former user: learn about the "Free Download Manager" ext.
