### ISSUE TITLE
Popup 排版错乱（文字超出范围）

### ISSUE THREAD

**Issue by Aetf** [RossWang/Aria2-Integration#9]
![image](https://user-images.githubusercontent.com/1519759/33585890-9fb9573a-d934-11e7-86d9-0e00d02ab265.png)
![image](https://user-images.githubusercontent.com/1519759/33585918-c0361bb0-d934-11e7-8d63-c0d84e06aaee.png)

也许跟我在 about:config 里设定了 `layout.css.devPixelsPerPx = 1.5` 有关？

**Comment by RossWang** [comment]
應該不是layout.css.devPixelsPerPx的關係，因為改變這個的話按鈕也會跟著變大，文字就塞得下去了

我沒有指定按鈕的文字大小，我是讓Firefox自己調整文字大小
我發現樓主的按鈕文字和輸入框文字特別大，是不是有用其他擴展改過啊？

這是我的大小
![default](https://user-images.githubusercontent.com/13231557/33721703-ba99ce0c-dba2-11e7-8ee1-fa85f5672137.png)

你看看你自行指定13.3px能不能改善，我再看看以後版本要不要指定13或14px

**Comment by Aetf** [comment]
我没自己改过字体大小。开了个新的 Profile 试了一下果然还是`layout.css.devPixelsPerPx`的关系。

当设置成自动的时候（-1，实际上就是2）字体是正常的
![image](https://user-images.githubusercontent.com/1519759/33778574-46e6dc28-dc17-11e7-99fc-ae9fce859572.png)
![image](https://user-images.githubusercontent.com/1519759/33778613-6df39540-dc17-11e7-9e29-13c8bbbb709d.png)

设置成1.5的时候字体就变成17.7px了
![image](https://user-images.githubusercontent.com/1519759/33778598-5ff84d78-dc17-11e7-8808-1e3e450bb85b.png)

我感觉这是 Firefox 的一个 bug，有时间我去报一下吧，这也不是什么大问题。。。

**Comment by RossWang** [comment]
Thanks for your help

Reference:
https://bugzilla.mozilla.org/show_bug.cgi?id=1081121
